// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzeria.Infrastructure.Data;

#nullable disable

namespace Pizzeria_Infrastructure.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20260710221939_AddImagenUrlPizza")]
    partial class AddImagenUrlPizza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pizzeria.Domain.Entities.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Clásica",
                            Descripcion = "Pizza clásica con salsa de tomate y queso muzzarella.",
                            ImagenUrl = "/img/muzzarella.jpg",
                            Nombre = "Muzzarella",
                            Precio = 5500m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Clásica",
                            Descripcion = "Pizza con tomate, ajo, orégano y muzzarella.",
                            ImagenUrl = "/img/napolitana.jpg",
                            Nombre = "Napolitana",
                            Precio = 6500m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Especial",
                            Descripcion = "Pizza con jamón, morrón y muzzarella.",
                            ImagenUrl = "/img/especial.jpg",
                            Nombre = "Especial",
                            Precio = 7500m
                        });
                });

            modelBuilder.Entity("Pizzeria.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pizzeria.com",
                            Nombre = "Administrador",
                            Password = "123456",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@pizzeria.com",
                            Nombre = "Usuario Demo",
                            Password = "123456",
                            Rol = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
